name = "abpn-study-cloudflare"
main = "src/worker.js"
compatibility_date = "2026-07-20"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "abpn-study-db"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"

[vars]
APP_ENV = "development"
